### ISSUE TITLE
Add support for percona-server version 5.6

### ISSUE THREAD

**Issue by tersmitten** [Oefenweb/ansible-percona-server#18]

**Comment by tersmitten** [comment]
* https://www.percona.com/doc/percona-server/5.6/diagnostics/response_time_distribution.html#response-time-distribution

**Comment by tersmitten** [comment]
@mvdriel Do you have more input on this?

**Comment by tersmitten** [comment]
https://www.percona.com/doc/percona-server/5.6/upgrading_guide_55_56.html

**Comment by tersmitten** [comment]
https://dev.mysql.com/doc/refman/5.6/en/upgrading-from-previous-series.html

**Comment by mvdriel** [comment]
https://www.percona.com/doc/percona-server/5.6/changed_in_56.html

**Comment by mvdriel** [comment]
https://www.percona.com/blog/2013/02/21/mysql-5-5-and-mysql-5-6-default-variable-values-differences/
