### ISSUE TITLE
Add support for percona-server version 5.7

### ISSUE THREAD

**Issue by tersmitten** [Oefenweb/ansible-percona-server#19]

**Comment by tersmitten** [comment]
https://www.digitalocean.com/community/tutorials/how-to-prepare-for-your-mysql-5-7-upgrade

**Comment by tersmitten** [comment]
https://dev.mysql.com/doc/refman/5.7/en/upgrading-from-previous-series.html

**Comment by ewlarson** [comment]
Is 5.7 a possibility, or should I look elsewhere?

**Comment by tersmitten** [comment]
I haven't tested it yet, but it's on my wishlist. Can you give it a try?

**Comment by ewlarson** [comment]
Hi again, I successfully deployed 5.7 on a Digital Ocean droplet.  Just needed to add 5.7 to the defaults/main.yml and vars/main.yml

Do you want a PR for these changes... they're just so tiny it feels almost unnecessary.

**Comment by tersmitten** [comment]
Feel free to make a PR, I rather have 5.6 as the default for now.

Thanks in advance
