### ISSUE TITLE
Add support for el7

### ISSUE THREAD

**Issue by divansantana** [Oefenweb/ansible-percona-server#38]
Would you accept a PR for centos 7 support?

Thinking about adding it to your project. Your project looks like the best percona-server one around.

**Comment by tersmitten** [comment]
If this role only needs minor adjustments I'm open to it, but otherwise we prefer not to add operating systems the we don't use / actively test.

**Comment by divansantana** [comment]
Understand. It makes sense for me not to add it. We'll do our own internal one - thanks.
