### ISSUE TITLE
Ability to define key server as variable

### ISSUE THREAD

**Issue by windbridges** [Oefenweb/ansible-percona-server#40]
Hi.
on fresh Debian 9 install I've faced with the following trouble. I getting an error on "repository | add public key" task, saying "gpg: keyserver receive failed: Server indicated a failure <Unspecified source> keyserver.ubuntu.com".

After a small research I found this answer - https://unix.stackexchange.com/questions/399027/gpg-keyserver-receive-failed-server-indicated-a-failure

The author of question gets slightly different error, but offered solution was helpful for me also. So I changed the line `keyserver: keyserver.ubuntu.com` to `keyserver: hkp://keyserver.ubuntu.com:80` in tasks/repository.yml and it solved the problem.

They say about some firewall there, but I did not understand what they mean. I did not install any firewalls into Debian, and searching for any firewall installed by default gets nothing to me (to be honest I do not know Linux systems so well). So if someone could tell me how to configure a firewall the right way (and which firewall exactly) it would be a good solution also.

But I think the easiest way to fix that is just by allowing user to specify `keyserver` value in configuration variable.

**Comment by tersmitten** [comment]
Feel free to make a pull request
